### ISSUE TITLE
feat-extract-n-grams function specification

### ISSUE THREAD

**Issue by joshsia** [UBC-MDS/pytextprep#4]

**Comment by joshsia** [comment]
I just noticed that @arijc76 wrote the function specification in another `.py` file. I think that all our functions should go in `pytextprep.py`.

**Comment by arijeetchatterjee** [comment]
@joshsia  I think it's a good idea to separate the different functionality in different .py files. Similar to the example in the individual assignment, where the word counting and plotting functions were in separate files. But if the consensus is to put all the code in one file, I'll change the code.

**Comment by joshsia** [comment]
@arijc76 Ah ok! In that case, should I change the filename where I wrote the `generate_cloud` function?

**Comment by arijeetchatterjee** [comment]
I guess changing the file name would be good in this case.

**Comment by joshsia** [comment]
Ok this has been done!
