### ISSUE TITLE
License choice justification

### ISSUE THREAD

**Issue by joshsia** [UBC-MDS/pytextprep#54]

**Comment by mmaidana24318** [comment]
As discussed in our team meeting, we agree to **keep the MIT license for both packages pyTextPrep and textprepr,** based on the following points:

1. The MIT license includes a limitation of liability that will provide protection for us as authors
2. It also allows us to claim copyright, which may be useful in the future for job searching or other purposes where we have to demonstrate ability
3. It encourages usage, distribution and modification of the software, which is aligned with our objective of turn this into a collaborative project and promote external contributions to improve the functionality of the package
4. None of the dependencies we have impose restrictions on the licensing model of our product
 
Please confirm in the thread below that you are in agreement with the decision as documented proof of this team decision.

**Comment by PhilsChan** [comment]
> As discussed in our team meeting, we agree to **keep the MIT license for both packages pyTextPrep and textprepr,** based on the following points:
> 
> 1. The MIT license includes a limitation of liability that will provide protection for us as authors
> 2. It also allows us to claim copyright, which may be useful in the future for job searching or other purposes where we have to demonstrate ability
> 3. It encourages usage, distribution and modification of the software, which is aligned with our objective of turn this into a collaborative project and promote external contributions to improve the functionality of the package
> 4. None of the dependencies we have impose restrictions on the licensing model of our product
>     
>    Please confirm in the thread below that you are in agreement with the decision as documented proof of this team decision.

Thanks for the input! I am totally aligned with your thoughts!

**Comment by joshsia** [comment]
Thanks for writing this up! I agree with the points that you mentioned.

**Comment by arijeetchatterjee** [comment]
Thanks for sharing this. I agree with all the points mentioned.
