### ISSUE TITLE
Edit CONDUCT.md to describe the code of conduct for contributing to your project

### ISSUE THREAD

**Issue by joshsia** [UBC-MDS/pytextprep#6]

**Comment by arijeetchatterjee** [comment]
As per the previous project, I believe we have to provide email addresses in the Conduct.md document. Using our UBC emails is good idea I think. @joshsia, @PhilsChan, @mmaidana24318, what is your ubc email?

* arijc@student.ubc.ca
* joshsia@student.ubc.ca
* khpchan@student.ubc.ca
*
